Update simple_workflow.yml

diff --git a/.github/workflows/simple_workflow.yml b/.github/workflows/simple_workflow.yml
--- a/.github/workflows/simple_workflow.yml
+++ b/.github/workflows/simple_workflow.yml
@@ -28,8 +28,8 @@ jobs:
         uses: actions/checkout@v2
         
       - name: Set job status as failed
-        if: ${{ failure() }}
-        run: exit 1
+        if: ${{ success() }}  # Check if the previous step was successful
+        run: exit 1  # Exit with a failure status
 
       - name: Notify Build Status
         if: always()
