Update simple_workflow.yml

diff --git a/.github/workflows/simple_workflow.yml b/.github/workflows/simple_workflow.yml
--- a/.github/workflows/simple_workflow.yml
+++ b/.github/workflows/simple_workflow.yml
@@ -1,30 +1,29 @@
 name: Simple Workflow
- 
+
 on:
   push:
     branches:
       - main
- 
+
 jobs:
   build-test-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Build
-        shell: bash
         run: echo "Building"
 
       - name: Test
-        shell: bash
         run: echo "Testing"
 
-      - name: Deploy
-        shell: bash
-        run: echo "Deploying"
+      - name: Error
+        run: |
+          echo "Error encountered, marking the job as failed."
+          exit 1  # Exit with a failure status
 
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Notify Build Status
+      - name: Call Build and Notify action
         uses: ./.github/actions/build_and_notify
         with:
           webhook-url: ${{ secrets.WEBHOOK_URL }}
@@ -32,3 +31,12 @@ jobs:
           error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
           success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
           success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
+        if: always()
+
+  handle-failure:
+    needs: build-test-deploy
+    runs-on: ubuntu-latest
+    if: ${{ needs.build-test-deploy.result != 'success' }}
+    steps:
+      - name: Set job status as failed
+        run: exit 1
