Update simple_workflow.yml

diff --git a/.github/workflows/simple_workflow.yml b/.github/workflows/simple_workflow.yml
--- a/.github/workflows/simple_workflow.yml
+++ b/.github/workflows/simple_workflow.yml
@@ -12,18 +12,24 @@ jobs:
       - name: Build
         shell: bash
         run: echo "Building"
-
+        
       - name: Test
         shell: bash
         run: echo "Testing"
-
-      #- name: Error
-      #  shell: bash
-      #  run: exit 1
+        
+      - name: Error
+        shell: bash
+        run: |
+          echo "Error encountered, marking the job as failed."
+          exit 1  # Exit with a failure status
 
       - name: Checkout repository
         if: always()
         uses: actions/checkout@v2
+        
+      - name: Set job status as failed
+        if: ${{ failure() }}
+        run: exit 1
 
       - name: Notify Build Status
         if: always()
